// <auto-generated />
using System;
using IndaloAventurApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndaloAventurApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610185654_AddSignalTitle")]
    partial class AddSignalTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndaloAventurApi.Domain.ClubPositions.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.FichasContacto.FichaContacto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FichasContacto", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.FichasSocio.FichaSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceptaCobroCuenta")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptaPoliticaPrivacidad")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptaUsoImagenes")
                        .HasColumnType("bit");

                    b.Property<string>("Alergias")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Poblacion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Tlf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FichasSocio", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.LicenciasFederativas.SolicitudLicenciaFederativa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TarifaLicenciaFederativaId")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TarifaLicenciaFederativaId");

                    b.HasIndex("UserId", "Temporada")
                        .IsUnique();

                    b.ToTable("SolicitudesLicenciasFederativas", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.LicenciasFederativas.TarifaLicenciaFederativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("PrecioClub")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioIndependiente")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.Property<string>("Territorio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Temporada", "Licencia", "Categoria")
                        .IsUnique();

                    b.ToTable("TarifasLicenciasFederativas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Mayores",
                            Licencia = "A",
                            PrecioClub = 45.0m,
                            PrecioIndependiente = 65.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Juveniles",
                            Licencia = "A",
                            PrecioClub = 11.0m,
                            PrecioIndependiente = 31.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Infantiles",
                            Licencia = "A",
                            PrecioClub = 11.0m,
                            PrecioIndependiente = 31.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Mayores",
                            Licencia = "A+",
                            PrecioClub = 58.0m,
                            PrecioIndependiente = 78.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Juveniles",
                            Licencia = "A+",
                            PrecioClub = 26.0m,
                            PrecioIndependiente = 46.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Infantiles",
                            Licencia = "A+",
                            PrecioClub = 26.0m,
                            PrecioIndependiente = 46.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Mayores",
                            Licencia = "A Familiar",
                            PrecioClub = 43.0m,
                            PrecioIndependiente = 63.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Juveniles",
                            Licencia = "A Familiar",
                            PrecioClub = 9.0m,
                            PrecioIndependiente = 29.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Infantiles",
                            Licencia = "A Familiar",
                            PrecioClub = 9.0m,
                            PrecioIndependiente = 29.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Mayores",
                            Licencia = "A-IS Inclusion Social",
                            PrecioClub = 19.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Juveniles",
                            Licencia = "A-IS Inclusion Social",
                            PrecioClub = 8.5m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Infantiles",
                            Licencia = "A-IS Inclusion Social",
                            PrecioClub = 8.5m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Mayores",
                            Licencia = "A+IS Inclusion Social",
                            PrecioClub = 33.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Juveniles",
                            Licencia = "A+IS Inclusion Social",
                            PrecioClub = 23.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Infantiles",
                            Licencia = "A+IS Inclusion Social",
                            PrecioClub = 23.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 16,
                            Categoria = "Mayores",
                            Licencia = "A ESP",
                            PrecioClub = 28.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 17,
                            Categoria = "Mayores",
                            Licencia = "A65",
                            PrecioClub = 32.0m,
                            PrecioIndependiente = 52.0m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 18,
                            Categoria = "Juveniles",
                            Licencia = "A REF",
                            PrecioClub = 8.5m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 19,
                            Categoria = "Infantiles",
                            Licencia = "A REF",
                            PrecioClub = 8.5m,
                            Temporada = 2026,
                            Territorio = "Andalucia, Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 20,
                            Categoria = "Mayores",
                            Licencia = "A NAC",
                            PrecioClub = 52.0m,
                            PrecioIndependiente = 72.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        },
                        new
                        {
                            Id = 21,
                            Categoria = "Juveniles",
                            Licencia = "A NAC",
                            PrecioClub = 22.0m,
                            PrecioIndependiente = 42.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        },
                        new
                        {
                            Id = 22,
                            Categoria = "Infantiles",
                            Licencia = "A NAC",
                            PrecioClub = 22.0m,
                            PrecioIndependiente = 42.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        },
                        new
                        {
                            Id = 23,
                            Categoria = "Mayores",
                            Licencia = "A NAC +",
                            PrecioClub = 69.0m,
                            PrecioIndependiente = 89.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        },
                        new
                        {
                            Id = 24,
                            Categoria = "Juveniles",
                            Licencia = "A NAC +",
                            PrecioClub = 36.0m,
                            PrecioIndependiente = 56.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        },
                        new
                        {
                            Id = 25,
                            Categoria = "Infantiles",
                            Licencia = "A NAC +",
                            PrecioClub = 36.0m,
                            PrecioIndependiente = 56.0m,
                            Temporada = 2026,
                            Territorio = "Espana, Andorra, Pirineo Frances, Portugal y Marruecos"
                        });
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Foto1")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Foto2")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("UserIdAlta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserIdModificacion")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.SignalComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SignalId", "FechaComentario");

                    b.ToTable("SignalComments", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.SignalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("SignalTypes", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Infrastructure.Security.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMember")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.FichasContacto.FichaContacto", b =>
                {
                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.TelefonoContacto", "Telefono1", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono1");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.TelefonoContacto", "Telefono2", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono2");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.DireccionContacto", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Direccion");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.EmailContacto", "Email", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.NombreContacto", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Nombre");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.OwnsOne("IndaloAventurApi.Domain.FichasContacto.ValueObjects.ObservacionesContacto", "Observaciones", b1 =>
                        {
                            b1.Property<Guid>("FichaContactoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Observaciones");

                            b1.HasKey("FichaContactoId");

                            b1.ToTable("FichasContacto");

                            b1.WithOwner()
                                .HasForeignKey("FichaContactoId");
                        });

                    b.Navigation("Direccion");

                    b.Navigation("Email");

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Observaciones");

                    b.Navigation("Telefono1")
                        .IsRequired();

                    b.Navigation("Telefono2");
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.FichasSocio.FichaSocio", b =>
                {
                    b.HasOne("IndaloAventurApi.Domain.ClubPositions.Cargo", null)
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.LicenciasFederativas.SolicitudLicenciaFederativa", b =>
                {
                    b.HasOne("IndaloAventurApi.Domain.LicenciasFederativas.TarifaLicenciaFederativa", "TarifaLicenciaFederativa")
                        .WithMany()
                        .HasForeignKey("TarifaLicenciaFederativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TarifaLicenciaFederativa");
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.Signal", b =>
                {
                    b.HasOne("IndaloAventurApi.Domain.TrailSignals.SignalType", "SignalType")
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SignalType");
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.SignalComment", b =>
                {
                    b.HasOne("IndaloAventurApi.Domain.TrailSignals.Signal", "Signal")
                        .WithMany("Comentarios")
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("IndaloAventurApi.Infrastructure.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("IndaloAventurApi.Infrastructure.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndaloAventurApi.Infrastructure.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("IndaloAventurApi.Infrastructure.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndaloAventurApi.Domain.TrailSignals.Signal", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
