name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'src/blazorapp/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore src/blazorapp/IndaloaventurApp.sln

      - name: Publish
        run: dotnet publish src/blazorapp/IndaloaventurApp.Web/IndaloaventurApp.Web/IndaloaventurApp.Web.csproj -c Release -o ./publish-frontend

      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish-frontend/
